### ISSUE TITLE
Improve Fans

### ISSUE THREAD

**Issue by narrative** [tz0/game#35]
- [x] Allow fan strength and fan distance of effect to be specified separately.
- [x] Fans should be blocked by walls.

**Comment by crombach** [comment]
Fans being blocked by walls isn't that big of a deal. Consider an alternate solution:
We have 3 parameters when we create a fan.

1. Fan origin strength
2. Fan end strength
3. Fan "force field" length

That way, we can have fans be affected by walls artificially (through level design rather than detecting walls on the fly).

**Comment by crombach** [comment]
In branch `fan-update`

**Comment by crombach** [comment]
Merged to master in #37
